### ISSUE TITLE
superfluous roles.meta file 

### ISSUE THREAD

**Issue by meinicke** [joliebig/featurehouse#30]
The roles.meta file is no longer used by FeatureIDE
I dont know if it is used elswhere.

If it is not used anymore, remove the creation of the file from FstGenComposer.run() and FstGenComposerExtension.build()
(alternatively provide a configuration option)

**Comment by alexrhein** [comment]
I still need the roles.meta file. It is used in my tool SPLverifier.
But I added a configuration option to featurehouse.
roles.meta is only generated if you call featurehouse with --export_roles_json .
